defaults:
  - _self_
  - augmentations: symmetric.yaml
  - wandb: private.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "simclr-mvtec-ad"
method: "simclr"
backbone:
  name: "resnet18"
method_kwargs:
  proj_hidden_dim: 2048
  proj_output_dim: 256
  temperature: 0.2
data:
  dataset: mvtec-ad
  train_path: "/home/RUS_CIP/st190519/my_work/code/ssl-aug-benchmark/learning/draem/datasets/mvtec/train"
  val_path: "/home/RUS_CIP/st190519/my_work/code/ssl-aug-benchmark/learning/draem/datasets/mvtec/val"
  format: "image_folder"
  num_workers: 4
optimizer:
  name: "lars"
  batch_size: 64
  lr: 0.25
  classifier_lr: 0.1
  weight_decay: 1e-4
  kwargs:
    clip_lr: True
    eta: 0.02
    exclude_bias_n_norm: True
scheduler:
  name: "warmup_cosine"
checkpoint:
  enabled: True
  dir: "trained_models"
  frequency: 1
auto_resume:
  enabled: True

# overwrite PL stuff
max_epochs: 250
devices: [0]
sync_batchnorm: False
accelerator: "gpu"
strategy: "ddp"
precision: 16-mixed
